# Generated by Django 5.2.3 on 2025-06-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='profile_image',
            field=models.ImageField(default='static/images/logo.png', upload_to='static/images/doctors/'),
        ),
    ]
