# Generated by Django 5.2.3 on 2025-06-20 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='static/images/logo.png', upload_to='static/images/staff/')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.profession')),
            ],
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
