# Generated by Django 5.2.3 on 2025-06-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_doctors_name_alter_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
