# Generated by Django 5.2.3 on 2025-06-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_doctors_salary_staff_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('phone_number', models.IntegerField()),
                ('address', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
