# Generated by Django 5.2.3 on 2025-06-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_gender_doctors_age_doctors_date_of_birth_staff_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='age',
        ),
    ]
