# Generated by Django 5.2.3 on 2025-06-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_remove_doctors_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='age',
        ),
    ]
