# Generated by Django 5.2.3 on 2025-06-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_product_bill_billitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='tota_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
