# Generated by Django 5.2.3 on 2025-06-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_bill_tota_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
