# Generated by Django 5.2.3 on 2025-06-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_billitem_amount_billitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
