# Generated by Django 5.2.3 on 2025-06-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_account_paymentmethod_upipayments_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('paid', 'Paid')], default='not_paid', max_length=10),
        ),
    ]
