# Generated by Django 5.2.3 on 2025-06-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
