# Generated by Django 5.2.3 on 2025-06-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('done', 'Done')], default='draft', max_length=10),
        ),
    ]
