# Generated by Django 5.2.3 on 2025-06-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0024_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
