# Generated by Django 5.2.3 on 2025-06-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_paymentmethod_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_account_name', models.CharField(max_length=100)),
                ('credit_ifsc_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DebitAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_account_name', models.CharField(max_length=100)),
                ('debit_ifsc_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
