# Generated by Django 5.2.3 on 2025-06-27 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0026_creditaccount_debitaccount_delete_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditaccount',
            old_name='credit_account_name',
            new_name='credit_account_number',
        ),
        migrations.RenameField(
            model_name='debitaccount',
            old_name='debit_account_name',
            new_name='debit_account_number',
        ),
    ]
