# Generated by Django 5.2.3 on 2025-06-27 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0027_rename_credit_account_name_creditaccount_credit_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='credit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.creditaccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='debit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.debitaccount'),
        ),
    ]
