# Generated by Django 5.2.3 on 2025-06-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0028_payment_credit_account_payment_debit_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
