# Generated by Django 5.2.3 on 2025-06-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0029_doctors_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
