# Generated by Django 5.2.3 on 2025-06-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0032_alter_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
