# Generated by Django 5.2.3 on 2025-06-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0033_contact_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
