# Generated by Django 5.2.3 on 2025-06-28 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0035_alter_hospital_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='tota_amount',
            new_name='amount',
        ),
    ]
