# Generated by Django 5.2.3 on 2025-06-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0037_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency_symbol',
            field=models.CharField(max_length=10),
        ),
    ]
