# Generated by Django 5.2.3 on 2025-06-30 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0039_alter_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.country'),
        ),
    ]
