# Generated by Django 5.2.3 on 2025-07-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0042_states_usersinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
