# Generated by Django 5.2.3 on 2025-07-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0043_alter_states_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinfo',
            name='city',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
