# Generated by Django 5.2.3 on 2025-07-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0045_department_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
    ]
