# Generated by Django 5.2.3 on 2025-07-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0046_hospital_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
