# Generated by Django 5.2.3 on 2025-07-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0047_hospital_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='hospital',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
